let currentPuzzle=null,currentTemplate=0,selected=null,placed={},seconds=0,running=true,timerId=null,hints=0,draggedTile=null,touchTile=null,didDrag=false,dragStartX=0,dragStartY=0;
const board=document.getElementById("board"),numbers=document.getElementById("numbers"),timer=document.getElementById("timer"),modal=document.getElementById("modal"),modalTitle=document.getElementById("modalTitle"),modalText=document.getElementById("modalText"),levelSelect=document.getElementById("levelSelect"),modeSelect=document.getElementById("modeSelect"),templateWrap=document.getElementById("templateWrap"),message=document.getElementById("message"),ghost=document.getElementById("dragGhost"),availableCount=document.getElementById("availableCount");
function key(r,c){return `${r}-${c}`}function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function calc(a,op,b){if(op==="+")return a+b;if(op==="−")return a-b;if(op==="×")return a*b;return null}
function makeEquation(){let ops=["+","−","×"];while(true){let op=ops[rnd(0,2)],a=rnd(1,18),b=rnd(1,12);if(op==="−"&&a<=b)[a,b]=[b,a];if(op==="×"){a=rnd(2,9);b=rnd(2,8)}let res=calc(a,op,b);if(res>0&&res<=99)return[a,op,b,"=",res]}}
function coords(line,i){return{r:line.r+(line.d==="v"?i:0),c:line.c+(line.d==="h"?i:0)}}
function eqWithKnown(idx,val){let ops=["+","−","×"];for(let t=0;t<500;t++){let op=ops[rnd(0,2)],a,b,res;if(idx===0){a=val;b=op==="×"?rnd(2,8):rnd(1,12);if(op==="−"&&a<=b)continue;res=calc(a,op,b)}else if(idx===2){b=val;a=op==="×"?rnd(2,9):rnd(1,18);if(op==="−"&&a<=b)continue;res=calc(a,op,b)}else{res=val;if(op==="+"){a=rnd(1,Math.max(1,res-1));b=res-a}else if(op==="−"){b=rnd(1,12);a=res+b}else{let ds=[];for(let d=2;d<=9;d++)if(res%d===0)ds.push(d);if(!ds.length)continue;a=ds[rnd(0,ds.length-1)];b=res/a}}if(res>0&&res<=99){let v=[a,op,b,"=",res];if(Number(v[idx])===val)return v}}return null}
function validLine(cells,line,v){for(let i=0;i<5;i++){let p=coords(line,i),old=cells[p.r]?.[p.c];if(p.r<0||p.r>=11||p.c<0||p.c>=11)return false;if(old!==""&&String(old)!==String(v[i]))return false}return true}
function makeLine(cells,line){for(let idx of [0,2,4]){let p=coords(line,idx),old=cells[p.r]?.[p.c];if(old!==""&&/^\d+$/.test(String(old)))return eqWithKnown(idx,Number(old))}return makeEquation()}
function generateAutoPuzzle(){
  const size=11,cells=Array.from({length:size},()=>Array(size).fill("")),solution={},hidden=[];
  const pattern=[
    {r:0,c:0,d:"h",hide:[0]},{r:0,c:4,d:"v",hide:[4]},
    {r:2,c:0,d:"h",hide:[2]},{r:2,c:2,d:"v",hide:[4]},
    {r:4,c:0,d:"h",hide:[0]},{r:4,c:4,d:"v",hide:[4]},
    {r:6,c:0,d:"h",hide:[2]},{r:6,c:4,d:"v",hide:[4]},
    {r:8,c:0,d:"h",hide:[0]},{r:8,c:4,d:"h",hide:[4]},
    {r:4,c:6,d:"h",hide:[2]},{r:2,c:8,d:"v",hide:[0]},
    {r:0,c:6,d:"h",hide:[4]}
  ];
  for(let line of pattern){let vals=null;for(let t=0;t<300;t++){let v=makeLine(cells,line);if(v&&validLine(cells,line,v)){vals=v;break}}if(vals){for(let i=0;i<5;i++){let p=coords(line,i);cells[p.r][p.c]=String(vals[i])}}}
  for(let line of pattern){for(let idx of line.hide){let p=coords(line,idx),v=cells[p.r][p.c],k=key(p.r,p.c);if(v!==""&&/^\d+$/.test(v)&&solution[k]===undefined){solution[k]=Number(v);hidden.push(Number(v));cells[p.r][p.c]=""}}}
  return{name:"Automático",size,hints:2,numbers:shuffle(hidden),cells,solution}
}
function setMessage(t,type=""){message.textContent=t;message.className="message"+(type?" "+type:"")}
function init(){FIXED_LEVELS.forEach((l,i)=>{let o=document.createElement("option");o.value=i;o.textContent=l.name;levelSelect.appendChild(o)});modeSelect.onchange=()=>{templateWrap.style.display=modeSelect.value==="template"?"flex":"none";restart()};levelSelect.onchange=()=>{currentTemplate=Number(levelSelect.value);restart()};document.getElementById("newAutoBtn").onclick=()=>{modeSelect.value="auto";templateWrap.style.display="none";restart()};document.getElementById("restartBtn").onclick=restart;document.getElementById("pauseBtn").onclick=pause;document.getElementById("modalBtn").onclick=resume;document.getElementById("checkBtn").onclick=checkAll;document.getElementById("hintBtn").onclick=useHint;templateWrap.style.display="none";restart();startTimer()}
function loadPuzzle(){currentPuzzle=modeSelect.value==="template"?JSON.parse(JSON.stringify(FIXED_LEVELS[currentTemplate])):generateAutoPuzzle()}
function buildBoard(){let p=currentPuzzle;board.innerHTML="";board.style.gridTemplateColumns=`repeat(${p.size},1fr)`;for(let r=0;r<p.size;r++)for(let c=0;c<p.size;c++){let val=p.cells[r]?.[c]??"",d=document.createElement("div");d.className=val===""?"cell blank":"cell";d.dataset.pos=key(r,c);if(p.solution[key(r,c)]!==undefined){d.className="cell slot";d.onclick=()=>selectSlot(d);d.addEventListener("dragover",e=>{e.preventDefault();d.classList.add("drag-over")});d.addEventListener("dragleave",()=>d.classList.remove("drag-over"));d.addEventListener("drop",e=>{e.preventDefault();d.classList.remove("drag-over");if(draggedTile){selectSlot(d);placeNumber(draggedTile)}})}else d.textContent=val;board.appendChild(d)}}
function buildNumbers(){numbers.innerHTML="";currentPuzzle.numbers.forEach((n,i)=>{let b=document.createElement("button");b.className="tile";b.textContent=n;b.dataset.index=i;b.dataset.value=n;b.draggable=true;b.onclick=()=>{if(didDrag){didDrag=false;return}if(!touchTile)placeByClick(b)};b.addEventListener("dragstart",()=>{draggedTile=b;b.classList.add("dragging")});b.addEventListener("dragend",()=>{draggedTile=null;b.classList.remove("dragging");document.querySelectorAll(".drag-over").forEach(x=>x.classList.remove("drag-over"))});b.addEventListener("pointerdown",startTouchDrag);numbers.appendChild(b)});updateHints();availableCount.textContent=`${currentPuzzle.numbers.length} para completar`}
function startTouchDrag(e){let btn=e.currentTarget;if(btn.classList.contains("used"))return;touchTile=btn;didDrag=false;dragStartX=e.clientX;dragStartY=e.clientY;const move=ev=>{let dx=Math.abs(ev.clientX-dragStartX),dy=Math.abs(ev.clientY-dragStartY);if(dx+dy>8){didDrag=true;ev.preventDefault();ghost.textContent=btn.dataset.value;ghost.classList.remove("hidden");moveGhost(ev.clientX,ev.clientY);markSlotUnder(ev.clientX,ev.clientY)}};const finish=ev=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",finish);document.removeEventListener("pointercancel",finish);let was=didDrag,slot=was?slotAt(ev.clientX,ev.clientY):null;ghost.classList.add("hidden");ghost.textContent="";document.querySelectorAll(".drag-over").forEach(x=>x.classList.remove("drag-over"));if(was&&slot){selectSlot(slot);placeNumber(btn)}else if(was)setMessage("Soltá el número sobre una casilla vacía.","error");touchTile=null;if(was){didDrag=true;setTimeout(()=>didDrag=false,220)}else didDrag=false};document.addEventListener("pointermove",move,{passive:false});document.addEventListener("pointerup",finish);document.addEventListener("pointercancel",finish)}
function moveGhost(x,y){ghost.style.left=x+"px";ghost.style.top=y+"px"}function slotAt(x,y){ghost.classList.add("hidden");let el=document.elementFromPoint(x,y);ghost.classList.remove("hidden");return el?.closest?.(".slot")}function markSlotUnder(x,y){document.querySelectorAll(".drag-over").forEach(s=>s.classList.remove("drag-over"));let s=slotAt(x,y);if(s)s.classList.add("drag-over")}
function selectSlot(d){document.querySelectorAll(".slot").forEach(x=>x.classList.remove("selected"));selected=d;selected.classList.add("selected")}
function placeByClick(b){if(!selected){let f=[...document.querySelectorAll(".slot")].find(x=>!x.textContent);if(f)selectSlot(f)}placeNumber(b)}
function returnOldTile(pos){if(placed[pos]!==undefined){let old=document.querySelector(`.tile[data-index="${placed[pos].index}"]`);if(old)old.classList.remove("used")}}
function placeNumber(b){if(!selected||b.classList.contains("used"))return;let pos=selected.dataset.pos,val=Number(b.dataset.value),cor=currentPuzzle.solution[pos];selected.classList.remove("correct","wrong");if(val!==cor){let prev=placed[pos]?.value??"";selected.textContent=val;selected.classList.add("wrong");setMessage("Error: ese número no corresponde a esa casilla.","error");setTimeout(()=>{let cell=document.querySelector(`.slot[data-pos="${pos}"]`);if(cell&&cell.classList.contains("wrong")){cell.textContent=prev;cell.classList.remove("wrong")}},650);return}returnOldTile(pos);selected.textContent=val;selected.classList.add("correct");placed[pos]={value:val,index:b.dataset.index};b.classList.add("used");setMessage("Correcto.","ok");if(isComplete())win();else{let next=[...document.querySelectorAll(".slot")].find(x=>!x.textContent);if(next)selectSlot(next)}}
function isComplete(){return[...document.querySelectorAll(".slot")].every(c=>Number(c.textContent)===currentPuzzle.solution[c.dataset.pos])}
function checkAll(){let ok=true;document.querySelectorAll(".slot").forEach(c=>{let pos=c.dataset.pos,val=Number(c.textContent);c.classList.remove("correct","wrong");if(!c.textContent||val!==currentPuzzle.solution[pos]){c.classList.add("wrong");ok=false}else c.classList.add("correct")});if(ok)win();else setMessage("Hay casillas vacías o incorrectas.","error")}
function useHint(){if(hints<=0)return;let target=[...document.querySelectorAll(".slot")].find(c=>Number(c.textContent)!==currentPuzzle.solution[c.dataset.pos]);if(!target)return;let pos=target.dataset.pos,cor=currentPuzzle.solution[pos],tile=[...document.querySelectorAll(".tile:not(.used)")].find(t=>Number(t.dataset.value)===cor);if(tile){selectSlot(target);returnOldTile(pos);target.textContent=cor;target.classList.add("correct");placed[pos]={value:cor,index:tile.dataset.index};tile.classList.add("used");hints--;updateHints();setMessage("Pista aplicada.","ok");if(isComplete())win()}}
function updateHints(){document.getElementById("hintsLeft").textContent="x"+hints}
function startTimer(){clearInterval(timerId);timerId=setInterval(()=>{if(!running)return;seconds++;let m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");timer.textContent=`${m}:${s}`},1000)}
function pause(){running=false;modalTitle.textContent="Pausa";modalText.textContent="Juego pausado.";modal.classList.remove("hidden")}function resume(){running=true;modal.classList.add("hidden")}function win(){running=false;modalTitle.textContent="¡Ganaste!";modalText.textContent=`Completaste el crucigrama en ${timer.textContent}.`;modal.classList.remove("hidden")}
function restart(){seconds=0;timer.textContent="00:00";running=true;selected=null;placed={};modal.classList.add("hidden");loadPuzzle();hints=currentPuzzle.hints;buildBoard();buildNumbers();setMessage("Arrastrá un número a una casilla vacía.")}
init();